Added command line arguments to specify running as a UDP message processor for RAF aircraft or other. There are now two threads spun up for this service.  They log to the following two files now: /tmp/udp2sql_raf.log /tmp/udp2sql_non.log
Added decrypting ablity which is used for other NOAA aircraft.  This implementation embeds native
Python code (provided by NOAA) into our c++ code.

See http://docs.python.org/2/c-api/ for details.

My initial attempt to embed Python into C++ encountered the following compiliation error:
/usr/include/python2.4/object.h:343: error: expected unqualified-id before ';' token
/usr/include/python2.4/object.h:343: error: abstract declarator 'PyObject*' used as declaration

Searching for this error message I found an answer to this thread which included the following patch:
http://svn.python.org/view/python/trunk/Include/object.h?rev=42531&r1=42410&r2=42531 

=====================
--- python/trunk/Include/object.h       2006/02/16 14:24:38     42410
+++ python/trunk/Include/object.h       2006/02/20 22:27:28     42531
@@ -345,7 +345,7 @@
 typedef struct _heaptypeobject {
        /* Note: there's a dependency on the order of these members
           in slotptr() in typeobject.c . */ 
-       PyTypeObject type; 
+       PyTypeObject ht_type;
        PyNumberMethods as_number;
        PyMappingMethods as_mapping;
        PySequenceMethods as_sequence; /* as_sequence comes after as_mapping,
@@ -354,13 +354,13 @@
                                          a given operator (e.g. __getitem__).
                                          see add_operators() in typeobject.c . */
        PyBufferProcs as_buffer;          
-       PyObject *name, *slots;
+       PyObject *ht_name, *ht_slots;
        /* here are optional user slots, followed by the members. */
 } PyHeapTypeObject;
 
 /* access macro to the members which are floating "behind" the object */
 #define PyHeapType_GET_MEMBERS(etype) \
-    ((PyMemberDef *)(((char *)etype) + (etype)->type.ob_type->tp_basicsize))
+    ((PyMemberDef *)(((char *)etype) + (etype)->ht_type.ob_type->tp_basicsize))


 /* Generic type check */
=====================

This patch reffers to this file:
-rw-r--r-- 1 root root 29625 Jan  9 04:48 /usr/include/python2.4/object.h

Applying this patch resolved the compiliation error.

Using this embedding process pre-compiled the Python code decrypt.py for me.

In the process of adding the '-R' and '-N' command line options I broke the
previous implementation that passed an additional specification string used
when connecting to the postgres database.  This wasn't used when running udp2sql
on eol-rt-data.  TODO - I'll need to fix this if udp2sql is used elsewhere,

svn path=/; revision=6750